name: Downstream Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  content-scan:
    # this calls the shared workflow in your shared repo
    uses: iamgini/ansible-content-scanning-pipeline/.github/workflows/content-scanning.yml@main
    with:
      path: "./"
    secrets: inherit
